-- Catalog seed: the 16 Spin & Go situations (12 3-max and 4 HU, ADR-0011), in presentation order, with the hero and
-- the prior actions of each one (ADR-0013).

INSERT INTO app.situation (key, position, label, format, hero, notes) VALUES
    ('btn_open', 1, 'BTN Open', '3max', 'BTN', NULL),
    ('sb_open', 2, 'SB Open (BTN fold)', '3max', 'SB', NULL),
    ('sb_vs_btn_mr', 3, 'SB vs BTN Min-Raise', '3max', 'SB', NULL),
    ('sb_vs_btn_limp', 4, 'SB vs BTN Limp', '3max', 'SB', NULL),
    ('bb_vs_sb_mr', 5, 'BB vs SB Min-Raise', '3max', 'BB', NULL),
    ('bb_vs_sb_limp', 6, 'BB vs SB Limp', '3max', 'BB', NULL),
    ('bb_vs_btn_mr_sb_fold', 7, 'BB vs BTN MR (SB fold)', '3max', 'BB', NULL),
    ('bb_vs_btn_limp_sb_fold', 8, 'BB vs BTN Limp (SB fold)', '3max', 'BB', NULL),
    ('bb_vs_btn_mr_sb_3bet', 9, 'BB vs BTN MR (SB 3bet)', '3max', 'BB', NULL),
    ('bb_vs_btn_limp_sb_3bet', 10, 'BB vs BTN Limp (SB 3bet)', '3max', 'BB', NULL),
    ('bb_vs_btn_mr_sb_call', 11, 'BB vs BTN MR (SB call)', '3max', 'BB', NULL),
    ('bb_vs_btn_limp_sb_call', 12, 'BB vs BTN Limp (SB call)', '3max', 'BB', NULL),
    ('hu_sb_open', 13, 'HU SB Open', 'hu', 'SB', NULL),
    ('hu_bb_vs_mr', 14, 'HU BB vs Min-Raise', 'hu', 'BB', NULL),
    ('hu_bb_vs_limp', 15, 'HU BB vs Limp', 'hu', 'BB', NULL),
    ('hu_bb_vs_os', 16, 'HU BB vs Open-Shove', 'hu', 'BB', NULL);

INSERT INTO app.situation_prior_action (situation, seq, position, action) VALUES
    ('sb_open', 1, 'BTN', 'FOLD'),
    ('sb_vs_btn_mr', 1, 'BTN', 'MIN_RAISE'),
    ('sb_vs_btn_limp', 1, 'BTN', 'LIMP'),
    ('bb_vs_sb_mr', 1, 'BTN', 'FOLD'),
    ('bb_vs_sb_mr', 2, 'SB', 'MIN_RAISE'),
    ('bb_vs_sb_limp', 1, 'BTN', 'FOLD'),
    ('bb_vs_sb_limp', 2, 'SB', 'LIMP'),
    ('bb_vs_btn_mr_sb_fold', 1, 'BTN', 'MIN_RAISE'),
    ('bb_vs_btn_mr_sb_fold', 2, 'SB', 'FOLD'),
    ('bb_vs_btn_limp_sb_fold', 1, 'BTN', 'LIMP'),
    ('bb_vs_btn_limp_sb_fold', 2, 'SB', 'FOLD'),
    ('bb_vs_btn_mr_sb_3bet', 1, 'BTN', 'MIN_RAISE'),
    ('bb_vs_btn_mr_sb_3bet', 2, 'SB', 'THREE_BET'),
    ('bb_vs_btn_limp_sb_3bet', 1, 'BTN', 'LIMP'),
    ('bb_vs_btn_limp_sb_3bet', 2, 'SB', 'RAISE'),
    ('bb_vs_btn_mr_sb_call', 1, 'BTN', 'MIN_RAISE'),
    ('bb_vs_btn_mr_sb_call', 2, 'SB', 'CALL'),
    ('bb_vs_btn_limp_sb_call', 1, 'BTN', 'LIMP'),
    ('bb_vs_btn_limp_sb_call', 2, 'SB', 'CALL'),
    ('hu_bb_vs_mr', 1, 'SB', 'MIN_RAISE'),
    ('hu_bb_vs_limp', 1, 'SB', 'LIMP'),
    ('hu_bb_vs_os', 1, 'SB', 'SHOVE');

INSERT INTO app.situation_stack (situation, stack) VALUES
    ('btn_open', 25),
    ('btn_open', 20),
    ('btn_open', 15),
    ('btn_open', 12),
    ('btn_open', 10),
    ('btn_open', 8),
    ('sb_open', 25),
    ('sb_open', 20),
    ('sb_open', 15),
    ('sb_open', 12),
    ('sb_open', 10),
    ('sb_open', 8),
    ('sb_vs_btn_mr', 25),
    ('sb_vs_btn_mr', 20),
    ('sb_vs_btn_mr', 15),
    ('sb_vs_btn_mr', 10),
    ('sb_vs_btn_limp', 25),
    ('sb_vs_btn_limp', 20),
    ('sb_vs_btn_limp', 15),
    ('bb_vs_sb_mr', 25),
    ('bb_vs_sb_mr', 20),
    ('bb_vs_sb_mr', 15),
    ('bb_vs_sb_mr', 10),
    ('bb_vs_sb_limp', 25),
    ('bb_vs_sb_limp', 20),
    ('bb_vs_sb_limp', 15),
    ('bb_vs_sb_limp', 10),
    ('bb_vs_btn_mr_sb_fold', 25),
    ('bb_vs_btn_mr_sb_fold', 20),
    ('bb_vs_btn_mr_sb_fold', 15),
    ('bb_vs_btn_mr_sb_fold', 10),
    ('bb_vs_btn_limp_sb_fold', 25),
    ('bb_vs_btn_limp_sb_fold', 20),
    ('bb_vs_btn_limp_sb_fold', 15),
    ('bb_vs_btn_limp_sb_fold', 10),
    ('bb_vs_btn_mr_sb_3bet', 25),
    ('bb_vs_btn_mr_sb_3bet', 12.5),
    ('bb_vs_btn_mr_sb_3bet', 10),
    ('bb_vs_btn_limp_sb_3bet', 25),
    ('bb_vs_btn_limp_sb_3bet', 20),
    ('bb_vs_btn_limp_sb_3bet', 15),
    ('bb_vs_btn_limp_sb_3bet', 10),
    ('bb_vs_btn_mr_sb_call', 25),
    ('bb_vs_btn_mr_sb_call', 20),
    ('bb_vs_btn_mr_sb_call', 15),
    ('bb_vs_btn_mr_sb_call', 10),
    ('bb_vs_btn_limp_sb_call', 25),
    ('bb_vs_btn_limp_sb_call', 20),
    ('bb_vs_btn_limp_sb_call', 15),
    ('bb_vs_btn_limp_sb_call', 10),
    ('hu_sb_open', 25),
    ('hu_sb_open', 20),
    ('hu_sb_open', 15),
    ('hu_sb_open', 12),
    ('hu_sb_open', 10),
    ('hu_sb_open', 8),
    ('hu_bb_vs_mr', 25),
    ('hu_bb_vs_mr', 20),
    ('hu_bb_vs_mr', 15),
    ('hu_bb_vs_mr', 10),
    ('hu_bb_vs_mr', 8),
    ('hu_bb_vs_limp', 25),
    ('hu_bb_vs_limp', 20),
    ('hu_bb_vs_limp', 15),
    ('hu_bb_vs_limp', 12),
    ('hu_bb_vs_limp', 10),
    ('hu_bb_vs_limp', 8),
    ('hu_bb_vs_os', 25),
    ('hu_bb_vs_os', 20),
    ('hu_bb_vs_os', 15),
    ('hu_bb_vs_os', 12),
    ('hu_bb_vs_os', 10),
    ('hu_bb_vs_os', 8);

INSERT INTO app.situation_action (situation, seq, action) VALUES
    ('btn_open', 1, 'MR_4B_C'),
    ('btn_open', 2, 'MR_C_C'),
    ('btn_open', 3, 'MR_C_F'),
    ('btn_open', 4, 'MR_F_F'),
    ('btn_open', 5, 'L_C_C'),
    ('btn_open', 6, 'L_C_F'),
    ('btn_open', 7, 'ALLIN'),
    ('btn_open', 8, 'FOLD'),
    ('sb_open', 1, 'MR_4B_C'),
    ('sb_open', 2, 'MR_C_C'),
    ('sb_open', 3, 'MR_C_F'),
    ('sb_open', 4, 'MR_F_F'),
    ('sb_open', 5, 'L_C_C'),
    ('sb_open', 6, 'L_C_F'),
    ('sb_open', 7, 'ALLIN'),
    ('sb_open', 8, 'FOLD'),
    ('sb_vs_btn_mr', 1, 'ALLIN'),
    ('sb_vs_btn_mr', 2, '3BET_C'),
    ('sb_vs_btn_mr', 3, 'CALL'),
    ('sb_vs_btn_mr', 4, 'FOLD'),
    ('sb_vs_btn_limp', 1, 'ALLIN'),
    ('sb_vs_btn_limp', 2, 'ISO_C'),
    ('sb_vs_btn_limp', 3, 'ISO_F'),
    ('sb_vs_btn_limp', 4, 'LIMP'),
    ('sb_vs_btn_limp', 5, 'FOLD'),
    ('bb_vs_sb_mr', 1, 'ALLIN'),
    ('bb_vs_sb_mr', 2, '3BET_C'),
    ('bb_vs_sb_mr', 3, 'CALL'),
    ('bb_vs_sb_mr', 4, 'CALL_VS_X2'),
    ('bb_vs_sb_mr', 5, 'FOLD'),
    ('bb_vs_sb_limp', 1, 'ALLIN'),
    ('bb_vs_sb_limp', 2, 'ISO_C'),
    ('bb_vs_sb_limp', 3, 'CHECK'),
    ('bb_vs_btn_mr_sb_fold', 1, 'ALLIN'),
    ('bb_vs_btn_mr_sb_fold', 2, '3BET'),
    ('bb_vs_btn_mr_sb_fold', 3, 'CALL'),
    ('bb_vs_btn_mr_sb_fold', 4, 'FOLD'),
    ('bb_vs_btn_limp_sb_fold', 1, 'ALLIN'),
    ('bb_vs_btn_limp_sb_fold', 2, 'ISO_C'),
    ('bb_vs_btn_limp_sb_fold', 3, 'CHECK'),
    ('bb_vs_btn_mr_sb_3bet', 1, 'ALLIN'),
    ('bb_vs_btn_mr_sb_3bet', 2, 'CALL'),
    ('bb_vs_btn_mr_sb_3bet', 3, 'FOLD'),
    ('bb_vs_btn_limp_sb_3bet', 1, 'ALLIN'),
    ('bb_vs_btn_limp_sb_3bet', 2, '3BET_C'),
    ('bb_vs_btn_limp_sb_3bet', 3, 'CALL'),
    ('bb_vs_btn_limp_sb_3bet', 4, 'FOLD'),
    ('bb_vs_btn_mr_sb_call', 1, 'ALLIN'),
    ('bb_vs_btn_mr_sb_call', 2, '3BET'),
    ('bb_vs_btn_mr_sb_call', 3, 'CALL'),
    ('bb_vs_btn_mr_sb_call', 4, 'FOLD'),
    ('bb_vs_btn_limp_sb_call', 1, 'ALLIN'),
    ('bb_vs_btn_limp_sb_call', 2, 'ISO_C'),
    ('bb_vs_btn_limp_sb_call', 3, 'CHECK'),
    ('hu_sb_open', 1, 'MR_4B_C'),
    ('hu_sb_open', 2, 'MR_C_C'),
    ('hu_sb_open', 3, 'MR_C_F'),
    ('hu_sb_open', 4, 'MR_F_F'),
    ('hu_sb_open', 5, 'L_PUSH'),
    ('hu_sb_open', 6, 'L_C_C'),
    ('hu_sb_open', 7, 'L_C_F'),
    ('hu_sb_open', 8, 'L_F'),
    ('hu_sb_open', 9, 'FOLD'),
    ('hu_bb_vs_mr', 1, 'ALLIN'),
    ('hu_bb_vs_mr', 2, '3BET_C'),
    ('hu_bb_vs_mr', 3, 'CALL'),
    ('hu_bb_vs_mr', 4, 'FOLD'),
    ('hu_bb_vs_limp', 1, 'ALLIN'),
    ('hu_bb_vs_limp', 2, 'ISO_C'),
    ('hu_bb_vs_limp', 3, 'ISO_F'),
    ('hu_bb_vs_limp', 4, 'CHECK'),
    ('hu_bb_vs_os', 1, 'CALL'),
    ('hu_bb_vs_os', 2, 'FOLD');
