-- The app is in English (ADR-0021): this migration translated the situation notes seeded by V2, V5 and V7. Those
-- notes were a third party's advice, since taken out of the repository (ADR-0024): no situation has notes any more
-- (V9 removes them where they had been seeded), so there is nothing left to translate.
